server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: status
            values: [running]

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'

      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

      - source_labels: ['__meta_docker_container_log_path']
        target_label: '__path__'

    pipeline_stages:
      - docker: {}

      - json:
          expressions:
            ts: Timestamp
            level_json: Level
            msg_json: MessageTemplate
            properties: Properties

      - json:
          source: properties
          expressions:
            context_json: SourceContext
            request_path: RequestPath

      - regex:
          expression: '^(?P<level_txt>\w+):\s+(?P<context_txt>[^\[]+)(?:\[(?P<event_id>\d+)\])?\s+(?P<msg_txt>.*)$'

      - labels:
          level_json:
          context_json:
          level_txt:
          context_txt:

      - timestamp:
          source: ts
          format: RFC3339
          action_on_failure: skip
